"""CustomTkinter GUI for batch anonymization.

Implementation lives in the gui_* sibling modules (helpers, app,
settings dialog, comparison window, small dialogs) - this file is
the public entry point. It re-imports the same upstream package
symbols the original single-file gui.py did (so `from gui import
ReviewItem` etc. - names only ever imported, never defined, at the
old top level - still resolve) plus every name actually defined in
the gui_* modules, so `from gui import X` keeps working unchanged."""

import sys

try:
    from .anonymizer import (
        PDF_OUTPUT_MODE_ORIGINAL_REDACTION,
        PDF_OUTPUT_MODE_REBUILT_REVIEW,
        PDF_OUTPUT_MODE_VISUAL,
        PDF_REDACTION_SCOPE_SAFE,
        PDF_REDACTION_SCOPE_STRICT,
        SUPPORTED_LABELS,
        BatchResult,
        anonymize_batch,
    )
    from .audit import AUDIT_CATEGORY_ORDER
    from .dependency_updates import (
        check_dependency_updates,
        install_package_update,
    )
    from .environment_check import (
        ENV_ITEM_LLM,
        ENV_ITEM_NER,
        ENV_ITEM_OCR,
        INSTALL_ACTION_OPEN_URL,
        INSTALL_ACTION_SPACY_MODEL,
        check_environment,
        install_ner_model,
    )
    from .file_readers import read_docx_file, read_txt_file
    from .file_writers import internal_artifacts_dir
    from .llm_review import LLM_STATUS_AVAILABLE, list_installed_models
    from .manual_redaction import (
        EMPTY_MANUAL_EDITS,
        MANUAL_REDACTION_LABEL,
        ManualEdits,
        ManualRect,
        apply_manual_redaction_count_to_report_text,
        apply_pending_overrides,
        compute_visible_redaction_rects,
        load_manual_edits,
        manual_edits_path,
        rect_info_key,
        regenerate_pdf_with_manual_overrides,
        save_manual_edits,
    )
    from .report import (
        BATCH_ERROR_EMPTY_TEXT_PDF,
        BATCH_ERROR_FILE_IO,
        BATCH_ERROR_MISSING_DEPENDENCY,
        BATCH_ERROR_OCR_FAILED,
        BATCH_ERROR_OCR_UNAVAILABLE,
        BATCH_ERROR_PROCESSING_FAILED,
        BATCH_ERROR_TEXT_DECODING,
        BATCH_ERROR_UNSUPPORTED_FILE_TYPE,
        DICTIONARY_STATUS_INVALID,
        DICTIONARY_STATUS_LOADED,
        DICTIONARY_STATUS_NOT_SELECTED,
    )
    from .review import (
        REVIEW_STATUS_APPROVED,
        REVIEW_STATUS_NEEDS_REVIEW,
        REVIEW_STATUS_REJECTED,
        ReviewItem,
        apply_review_statuses,
        export_approved_workspace,
        load_review_workspace,
        preferred_review_output_path,
        save_review_files,
    )
except ImportError:
    from anonymizer import (
        PDF_OUTPUT_MODE_ORIGINAL_REDACTION,
        PDF_OUTPUT_MODE_REBUILT_REVIEW,
        PDF_OUTPUT_MODE_VISUAL,
        PDF_REDACTION_SCOPE_SAFE,
        PDF_REDACTION_SCOPE_STRICT,
        SUPPORTED_LABELS,
        BatchResult,
        anonymize_batch,
    )
    from audit import AUDIT_CATEGORY_ORDER
    from dependency_updates import (
        check_dependency_updates,
        install_package_update,
    )
    from environment_check import (
        ENV_ITEM_LLM,
        ENV_ITEM_NER,
        ENV_ITEM_OCR,
        INSTALL_ACTION_OPEN_URL,
        INSTALL_ACTION_SPACY_MODEL,
        check_environment,
        install_ner_model,
    )
    from file_readers import read_docx_file, read_txt_file
    from file_writers import internal_artifacts_dir
    from llm_review import LLM_STATUS_AVAILABLE, list_installed_models
    from manual_redaction import (
        EMPTY_MANUAL_EDITS,
        MANUAL_REDACTION_LABEL,
        ManualEdits,
        ManualRect,
        apply_manual_redaction_count_to_report_text,
        apply_pending_overrides,
        compute_visible_redaction_rects,
        load_manual_edits,
        manual_edits_path,
        rect_info_key,
        regenerate_pdf_with_manual_overrides,
        save_manual_edits,
    )
    from report import (
        BATCH_ERROR_EMPTY_TEXT_PDF,
        BATCH_ERROR_FILE_IO,
        BATCH_ERROR_MISSING_DEPENDENCY,
        BATCH_ERROR_OCR_FAILED,
        BATCH_ERROR_OCR_UNAVAILABLE,
        BATCH_ERROR_PROCESSING_FAILED,
        BATCH_ERROR_TEXT_DECODING,
        BATCH_ERROR_UNSUPPORTED_FILE_TYPE,
        DICTIONARY_STATUS_INVALID,
        DICTIONARY_STATUS_LOADED,
        DICTIONARY_STATUS_NOT_SELECTED,
    )
    from review import (
        REVIEW_STATUS_APPROVED,
        REVIEW_STATUS_NEEDS_REVIEW,
        REVIEW_STATUS_REJECTED,
        ReviewItem,
        apply_review_statuses,
        export_approved_workspace,
        load_review_workspace,
        preferred_review_output_path,
        save_review_files,
    )


try:
    from .gui_app import (
        AnonymizerApp,
    )
    from .gui_comparison_window import (
        BASE_PREVIEW_WIDTH,
        ZOOM_DEFAULT,
        ZOOM_MAX,
        ZOOM_MIN,
        ZOOM_STEP,
        ComparisonWindow,
        _render_text_block,
        canvas_point_to_pdf_point,
        clamp_zoom_level,
        ctk_widget_scaling_factor,
        find_rect_at_point,
        is_degenerate_drag_rect,
        normalize_drag_rect,
        pdf_page_zoom,
        render_document_preview,
        scroll_sync_units,
        zoom_link_glyph,
        zoom_link_tooltip_text,
        zoom_percent_label,
        zoom_step_from_scroll_event,
    )
    from .gui_dialogs import (
        AboutDialog,
        ApprovalLockWarningDialog,
        SummaryDialog,
    )
    from .gui_helpers import (
        _FILE_TYPE_ICON_CACHE,
        APP_ABOUT_TEXT,
        APP_ICON_ICO_PATH,
        APP_ICON_PATH,
        APP_PERSONAL_NOTE,
        APP_SUBTITLE,
        APP_TAGLINE,
        APP_TITLE,
        APP_USER_MODEL_ID,
        APP_VERSION,
        APPROVAL_LOCK_HINT_ID,
        BATCH_ERROR_LABELS_PL,
        CATEGORY_LABELS_PL,
        COLOR_ACCENT,
        COLOR_ACCENT_HOVER,
        COLOR_ACCENT_SOFT,
        COLOR_BG,
        COLOR_BORDER,
        COLOR_CARD,
        COLOR_HIGH_RISK,
        COLOR_HIGH_RISK_SOFT,
        COLOR_ICON_IDLE,
        COLOR_NEEDS_REVIEW,
        COLOR_NEEDS_REVIEW_SOFT,
        COLOR_OK,
        COLOR_OK_SOFT,
        COLOR_PRIMARY,
        COLOR_PRIMARY_SOFT,
        COLOR_TEXT,
        COLOR_TEXT_MUTED,
        COLOR_WARNING,
        COLOR_WARNING_SOFT,
        COLOR_WARNING_TEXT,
        DEFAULT_OUTPUT_SUBDIR_NAME,
        FILE_LIST_MAX_HEIGHT,
        FILE_TYPE_COLORS,
        FONT_FAMILY,
        HEADER_STACK_BREAKPOINT,
        LEGEND_ITEMS,
        LLM_MODELS_FOUND_HINT,
        LLM_NO_MODELS_HINT,
        MANUAL_REVIEW_WARNING,
        PDF_OUTPUT_LABEL_ORIGINAL_SAFE,
        PDF_OUTPUT_LABEL_ORIGINAL_STRICT,
        PDF_OUTPUT_LABEL_REBUILT_REVIEW,
        PDF_OUTPUT_LABEL_VISUAL_REDACTION,
        PDF_OUTPUT_SETTINGS_BY_LABEL,
        PDF_OUTPUT_SHORT_LABELS,
        PDF_REDACTION_SCOPE_LABELS,
        QUICK_SETTINGS_MIN_WIDTH,
        QUICK_SETTINGS_PANEL_WIDTH,
        RECENT_FOLDERS_MAX,
        RISK_STYLES,
        RISK_SUMMARY_TEXT_PL,
        SCRIPT_FONT_FAMILY,
        SELECTED_FILE_LIST_HEIGHT,
        SUPPORTED_EXTENSIONS,
        WINDOW_DEFAULT_SIZE,
        WINDOW_MIN_HEIGHT,
        WINDOW_MIN_WIDTH,
        ZOOM_LINK_HINT_ID,
        DnDCTk,
        IconTooltip,
        _bring_window_to_front,
        _draw_file_type_icon,
        _file_word,
        _pl_document_word,
        _pl_file_word,
        apply_subtle_scrollbar,
        batch_error_label_pl,
        category_label_pl,
        default_output_directory,
        dismiss_hint,
        environment_status_lookup,
        file_type_badge,
        filter_supported_paths,
        format_anonymize_button_text,
        format_anonymize_readiness,
        format_approval_lock_warning_text,
        format_approval_lock_warning_title,
        format_approved_export_status,
        format_audit_result,
        format_batch_audit_result,
        format_batch_dictionary_result,
        format_batch_error_items,
        format_batch_status,
        format_counters,
        format_dictionary_result,
        format_drop_result,
        format_llm_model_selector_state,
        format_processing_status,
        format_readiness_pl,
        format_recent_folder_timestamp,
        format_review_heading_subtitle,
        format_review_summary_line,
        format_safe_path_list,
        format_selected_file_count,
        format_short_path,
        get_file_type_icon,
        hint_is_dismissed,
        history_config_path,
        load_recent_folders,
        load_seen_hints,
        mousewheel_scroll_units,
        open_path_with_default_app,
        parse_dropped_file_paths,
        parse_report_summary,
        pdf_output_mode_from_gui_label,
        pdf_redaction_scope_from_gui_label,
        record_recent_folder,
        remove_paths_by_indexes,
        restore_hint,
        restrict_review_items_to_batch,
        review_status_label_pl,
        risk_style_key,
        save_recent_folders,
        save_seen_hints,
        truncate_filename_middle,
        ui_hints_config_path,
    )
    from .gui_settings_dialog import (
        SettingsDialog,
    )
except ImportError:
    from gui_app import (
        AnonymizerApp,
    )
    from gui_comparison_window import (
        BASE_PREVIEW_WIDTH,
        ZOOM_DEFAULT,
        ZOOM_MAX,
        ZOOM_MIN,
        ZOOM_STEP,
        ComparisonWindow,
        _render_text_block,
        canvas_point_to_pdf_point,
        clamp_zoom_level,
        ctk_widget_scaling_factor,
        find_rect_at_point,
        is_degenerate_drag_rect,
        normalize_drag_rect,
        pdf_page_zoom,
        render_document_preview,
        scroll_sync_units,
        zoom_link_glyph,
        zoom_link_tooltip_text,
        zoom_percent_label,
        zoom_step_from_scroll_event,
    )
    from gui_dialogs import (
        AboutDialog,
        ApprovalLockWarningDialog,
        SummaryDialog,
    )
    from gui_helpers import (
        _FILE_TYPE_ICON_CACHE,
        APP_ABOUT_TEXT,
        APP_ICON_ICO_PATH,
        APP_ICON_PATH,
        APP_PERSONAL_NOTE,
        APP_SUBTITLE,
        APP_TAGLINE,
        APP_TITLE,
        APP_USER_MODEL_ID,
        APP_VERSION,
        APPROVAL_LOCK_HINT_ID,
        BATCH_ERROR_LABELS_PL,
        CATEGORY_LABELS_PL,
        COLOR_ACCENT,
        COLOR_ACCENT_HOVER,
        COLOR_ACCENT_SOFT,
        COLOR_BG,
        COLOR_BORDER,
        COLOR_CARD,
        COLOR_HIGH_RISK,
        COLOR_HIGH_RISK_SOFT,
        COLOR_ICON_IDLE,
        COLOR_NEEDS_REVIEW,
        COLOR_NEEDS_REVIEW_SOFT,
        COLOR_OK,
        COLOR_OK_SOFT,
        COLOR_PRIMARY,
        COLOR_PRIMARY_SOFT,
        COLOR_TEXT,
        COLOR_TEXT_MUTED,
        COLOR_WARNING,
        COLOR_WARNING_SOFT,
        COLOR_WARNING_TEXT,
        DEFAULT_OUTPUT_SUBDIR_NAME,
        FILE_LIST_MAX_HEIGHT,
        FILE_TYPE_COLORS,
        FONT_FAMILY,
        HEADER_STACK_BREAKPOINT,
        LEGEND_ITEMS,
        LLM_MODELS_FOUND_HINT,
        LLM_NO_MODELS_HINT,
        MANUAL_REVIEW_WARNING,
        PDF_OUTPUT_LABEL_ORIGINAL_SAFE,
        PDF_OUTPUT_LABEL_ORIGINAL_STRICT,
        PDF_OUTPUT_LABEL_REBUILT_REVIEW,
        PDF_OUTPUT_LABEL_VISUAL_REDACTION,
        PDF_OUTPUT_SETTINGS_BY_LABEL,
        PDF_OUTPUT_SHORT_LABELS,
        PDF_REDACTION_SCOPE_LABELS,
        QUICK_SETTINGS_MIN_WIDTH,
        QUICK_SETTINGS_PANEL_WIDTH,
        RECENT_FOLDERS_MAX,
        RISK_STYLES,
        RISK_SUMMARY_TEXT_PL,
        SCRIPT_FONT_FAMILY,
        SELECTED_FILE_LIST_HEIGHT,
        SUPPORTED_EXTENSIONS,
        WINDOW_DEFAULT_SIZE,
        WINDOW_MIN_HEIGHT,
        WINDOW_MIN_WIDTH,
        ZOOM_LINK_HINT_ID,
        DnDCTk,
        IconTooltip,
        _bring_window_to_front,
        _draw_file_type_icon,
        _file_word,
        _pl_document_word,
        _pl_file_word,
        apply_subtle_scrollbar,
        batch_error_label_pl,
        category_label_pl,
        default_output_directory,
        dismiss_hint,
        environment_status_lookup,
        file_type_badge,
        filter_supported_paths,
        format_anonymize_button_text,
        format_anonymize_readiness,
        format_approval_lock_warning_text,
        format_approval_lock_warning_title,
        format_approved_export_status,
        format_audit_result,
        format_batch_audit_result,
        format_batch_dictionary_result,
        format_batch_error_items,
        format_batch_status,
        format_counters,
        format_dictionary_result,
        format_drop_result,
        format_llm_model_selector_state,
        format_processing_status,
        format_readiness_pl,
        format_recent_folder_timestamp,
        format_review_heading_subtitle,
        format_review_summary_line,
        format_safe_path_list,
        format_selected_file_count,
        format_short_path,
        get_file_type_icon,
        hint_is_dismissed,
        history_config_path,
        load_recent_folders,
        load_seen_hints,
        mousewheel_scroll_units,
        open_path_with_default_app,
        parse_dropped_file_paths,
        parse_report_summary,
        pdf_output_mode_from_gui_label,
        pdf_redaction_scope_from_gui_label,
        record_recent_folder,
        remove_paths_by_indexes,
        restore_hint,
        restrict_review_items_to_batch,
        review_status_label_pl,
        risk_style_key,
        save_recent_folders,
        save_seen_hints,
        truncate_filename_middle,
        ui_hints_config_path,
    )
    from gui_settings_dialog import (
        SettingsDialog,
    )


__all__ = [
    "APPROVAL_LOCK_HINT_ID",
    "APP_ABOUT_TEXT",
    "APP_ICON_ICO_PATH",
    "APP_ICON_PATH",
    "APP_PERSONAL_NOTE",
    "APP_SUBTITLE",
    "APP_TAGLINE",
    "APP_TITLE",
    "APP_USER_MODEL_ID",
    "APP_VERSION",
    "AUDIT_CATEGORY_ORDER",
    "BASE_PREVIEW_WIDTH",
    "BATCH_ERROR_EMPTY_TEXT_PDF",
    "BATCH_ERROR_FILE_IO",
    "BATCH_ERROR_LABELS_PL",
    "BATCH_ERROR_MISSING_DEPENDENCY",
    "BATCH_ERROR_OCR_FAILED",
    "BATCH_ERROR_OCR_UNAVAILABLE",
    "BATCH_ERROR_PROCESSING_FAILED",
    "BATCH_ERROR_TEXT_DECODING",
    "BATCH_ERROR_UNSUPPORTED_FILE_TYPE",
    "CATEGORY_LABELS_PL",
    "COLOR_ACCENT",
    "COLOR_ACCENT_HOVER",
    "COLOR_ACCENT_SOFT",
    "COLOR_BG",
    "COLOR_BORDER",
    "COLOR_CARD",
    "COLOR_HIGH_RISK",
    "COLOR_HIGH_RISK_SOFT",
    "COLOR_ICON_IDLE",
    "COLOR_NEEDS_REVIEW",
    "COLOR_NEEDS_REVIEW_SOFT",
    "COLOR_OK",
    "COLOR_OK_SOFT",
    "COLOR_PRIMARY",
    "COLOR_PRIMARY_SOFT",
    "COLOR_TEXT",
    "COLOR_TEXT_MUTED",
    "COLOR_WARNING",
    "COLOR_WARNING_SOFT",
    "COLOR_WARNING_TEXT",
    "DEFAULT_OUTPUT_SUBDIR_NAME",
    "DICTIONARY_STATUS_INVALID",
    "DICTIONARY_STATUS_LOADED",
    "DICTIONARY_STATUS_NOT_SELECTED",
    "EMPTY_MANUAL_EDITS",
    "ENV_ITEM_LLM",
    "ENV_ITEM_NER",
    "ENV_ITEM_OCR",
    "FILE_LIST_MAX_HEIGHT",
    "FILE_TYPE_COLORS",
    "FONT_FAMILY",
    "HEADER_STACK_BREAKPOINT",
    "INSTALL_ACTION_OPEN_URL",
    "INSTALL_ACTION_SPACY_MODEL",
    "LEGEND_ITEMS",
    "LLM_MODELS_FOUND_HINT",
    "LLM_NO_MODELS_HINT",
    "LLM_STATUS_AVAILABLE",
    "MANUAL_REDACTION_LABEL",
    "MANUAL_REVIEW_WARNING",
    "PDF_OUTPUT_LABEL_ORIGINAL_SAFE",
    "PDF_OUTPUT_LABEL_ORIGINAL_STRICT",
    "PDF_OUTPUT_LABEL_REBUILT_REVIEW",
    "PDF_OUTPUT_LABEL_VISUAL_REDACTION",
    "PDF_OUTPUT_MODE_ORIGINAL_REDACTION",
    "PDF_OUTPUT_MODE_REBUILT_REVIEW",
    "PDF_OUTPUT_MODE_VISUAL",
    "PDF_OUTPUT_SETTINGS_BY_LABEL",
    "PDF_OUTPUT_SHORT_LABELS",
    "PDF_REDACTION_SCOPE_LABELS",
    "PDF_REDACTION_SCOPE_SAFE",
    "PDF_REDACTION_SCOPE_STRICT",
    "QUICK_SETTINGS_MIN_WIDTH",
    "QUICK_SETTINGS_PANEL_WIDTH",
    "RECENT_FOLDERS_MAX",
    "REVIEW_STATUS_APPROVED",
    "REVIEW_STATUS_NEEDS_REVIEW",
    "REVIEW_STATUS_REJECTED",
    "RISK_STYLES",
    "RISK_SUMMARY_TEXT_PL",
    "SCRIPT_FONT_FAMILY",
    "SELECTED_FILE_LIST_HEIGHT",
    "SUPPORTED_EXTENSIONS",
    "SUPPORTED_LABELS",
    "WINDOW_DEFAULT_SIZE",
    "WINDOW_MIN_HEIGHT",
    "WINDOW_MIN_WIDTH",
    "ZOOM_DEFAULT",
    "ZOOM_LINK_HINT_ID",
    "ZOOM_MAX",
    "ZOOM_MIN",
    "ZOOM_STEP",
    "_FILE_TYPE_ICON_CACHE",
    "AboutDialog",
    "AnonymizerApp",
    "ApprovalLockWarningDialog",
    "BatchResult",
    "ComparisonWindow",
    "DnDCTk",
    "IconTooltip",
    "ManualEdits",
    "ManualRect",
    "ReviewItem",
    "SettingsDialog",
    "SummaryDialog",
    "_bring_window_to_front",
    "_draw_file_type_icon",
    "_file_word",
    "_pl_document_word",
    "_pl_file_word",
    "_render_text_block",
    "_set_windows_app_user_model_id",
    "anonymize_batch",
    "apply_manual_redaction_count_to_report_text",
    "apply_pending_overrides",
    "apply_review_statuses",
    "apply_subtle_scrollbar",
    "batch_error_label_pl",
    "canvas_point_to_pdf_point",
    "category_label_pl",
    "check_dependency_updates",
    "check_environment",
    "clamp_zoom_level",
    "compute_visible_redaction_rects",
    "ctk_widget_scaling_factor",
    "default_output_directory",
    "dismiss_hint",
    "environment_status_lookup",
    "export_approved_workspace",
    "file_type_badge",
    "filter_supported_paths",
    "find_rect_at_point",
    "format_anonymize_button_text",
    "format_anonymize_readiness",
    "format_approval_lock_warning_text",
    "format_approval_lock_warning_title",
    "format_approved_export_status",
    "format_audit_result",
    "format_batch_audit_result",
    "format_batch_dictionary_result",
    "format_batch_error_items",
    "format_batch_status",
    "format_counters",
    "format_dictionary_result",
    "format_drop_result",
    "format_llm_model_selector_state",
    "format_processing_status",
    "format_readiness_pl",
    "format_recent_folder_timestamp",
    "format_review_heading_subtitle",
    "format_review_summary_line",
    "format_safe_path_list",
    "format_selected_file_count",
    "format_short_path",
    "get_file_type_icon",
    "hint_is_dismissed",
    "history_config_path",
    "install_ner_model",
    "install_package_update",
    "internal_artifacts_dir",
    "is_degenerate_drag_rect",
    "list_installed_models",
    "load_manual_edits",
    "load_recent_folders",
    "load_review_workspace",
    "load_seen_hints",
    "main",
    "manual_edits_path",
    "mousewheel_scroll_units",
    "normalize_drag_rect",
    "open_path_with_default_app",
    "parse_dropped_file_paths",
    "parse_report_summary",
    "pdf_output_mode_from_gui_label",
    "pdf_page_zoom",
    "pdf_redaction_scope_from_gui_label",
    "preferred_review_output_path",
    "read_docx_file",
    "read_txt_file",
    "record_recent_folder",
    "rect_info_key",
    "regenerate_pdf_with_manual_overrides",
    "remove_paths_by_indexes",
    "render_document_preview",
    "restore_hint",
    "restrict_review_items_to_batch",
    "review_status_label_pl",
    "risk_style_key",
    "save_manual_edits",
    "save_recent_folders",
    "save_review_files",
    "save_seen_hints",
    "scroll_sync_units",
    "start_gui",
    "truncate_filename_middle",
    "ui_hints_config_path",
    "zoom_link_glyph",
    "zoom_link_tooltip_text",
    "zoom_percent_label",
    "zoom_step_from_scroll_event",
]


def _set_windows_app_user_model_id() -> None:
    """Give this process its own taskbar identity on Windows.

    Never fatal - a failure here only means the taskbar icon may fall
    back to python.exe's generic one, not that the app can't run. Must
    run before the first window is created (see _load_app_icon's
    docstring for why).
    """
    if sys.platform != "win32":
        return
    try:
        import ctypes

        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
            APP_USER_MODEL_ID
        )
    except (OSError, AttributeError):
        pass


def start_gui() -> None:
    """Start the CustomTkinter desktop application."""
    _set_windows_app_user_model_id()
    root = DnDCTk()
    AnonymizerApp(root)
    root.mainloop()


def main() -> None:
    """Run the GUI when this module is executed as a script."""
    start_gui()


if __name__ == "__main__":
    main()
